### ISSUE TITLE
excess using fluff

### ISSUE THREAD

**Issue by DickBaker** [Wintellect/WintellectWebinars#10]
in Demo04 the packages.config includes Newtonsoft.Json needed for JObject deserialisation in FixerService.GetRate but this code file has excess using statements
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using System.Net; 

ditto Program.cs has excess
using System.Linq;
using System.Text;

ditto OerService.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

and so on.

It's a particular mission of mine to encourage developers and trainers to eliminate excess stuff that makes code more complicated that necessary and deflects brainpower (I got too little of that left alas).

PLEASE do the simple [built-in] refactoring to simplify code [hey its easy in Roslyn era] both for newbies and senior citizens like me <grin/>

BTW why do you choose to use packages.config instead of normal [References Nuget] approach
- surely packages are so VS2015 ?!

**Comment by JohnWintellect** [comment]
Hey @bellj do you want to take a look at this issue?

**Comment by bellj** [comment]
There is no doubt that there are some using statements that are unnecessary. These using statements were added by Visual Studio as part of the default file templates since they are namespaces that contain types that are typically used in most applications. This increases developer productivity by not having to add common namespaces when adding additional code. These using statements of course have zero effect on the compiled product (does not make the binary any bigger or slower). So, in my "real" projects, I like to leave them in there since the chances are pretty good that I'll use something link LINQ at some point down the road as the project evolves. I have a hard time accepting the premise that it makes the code more "complicated". Having said all of that, I am also a fan of distilling down demonstration code to the absolute minimum necessary to fully illustrate the topic at hand. So, I will try to remember to remove them in the future. Thanks for the feedback!

Regarding the PackageReference feature, this is not enabled by default in VS2017 for projects other than .NET Standard libraries and .NET Core projects and is still not fully supported for some project types. Therefore, packages.config is used in the console-based demos and PackageReference is used in the ASP.NET Core demo (Demo05).
